name: Build Release

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose

      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: picturs
          path: target/release
